owner: d4khosting 
repo: uptime-d4k-li 

sites:
  - name: D4K Link Shortener Service
    url: https://d4k.li
    slug: d4k-li
    icon: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-favicon.svg

assignees:
  - pkiff

i18n:
  locale: en-CA

status-website:
  cname: d4kli.d4kstatus.net
  favicon: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-favicon-192x192.png
  faviconSvg: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-favicon.svg
  logoUrl: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-logo-2023.svg
  links:
    - rel: preconnect
      href: https://fonts.googleapis.com
    - rel: preconnect
      href: https://fonts.gstatic.com
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&display=swap
    - rel: stylesheet
      href: https://d4khosting.github.io/uptime-assets/css/d4k-status.css
  name: D4K Link Shortener Uptime Status
  introTitle: "**Uptime Status for D4K Link Shortener Service**"
  introMessage: Real-time status and historical uptime records for the D4K Link Shortener service. If the service is down, check the [D4K Hosting Status](https://www.d4kstatus.net/) page for updates.
  metaTags:
    - name: "robots"
      content: "noindex"
